### ISSUE TITLE
No module named 'typhon.nonlte.version'

### ISSUE THREAD

**Issue by JohnMrziglod** [atmtools/typhon#111]
### Bug summary

typhon tries to import the module typhon.nonlte.version which does not exist. The problem is in commit https://github.com/atmtools/typhon/pull/108/commits/84c04424e23739129dc358e1ed1b5bde8d3c0fdc

### Code for reproduction

```python
import typhon
```

### Actual outcome

```
Traceback (most recent call last):
  File "/dev/shm/u237002/anaconda36/envs/python36/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-7a30c66f0630>", line 1, in <module>
    import typhon
  File "/scratch/uni/u237/users/jmrziglod/projects/typhon/typhon/__init__.py", line 20, in <module>
    from . import nonlte
  File "/scratch/uni/u237/users/jmrziglod/projects/typhon/typhon/nonlte/__init__.py", line 4, in <module>
    from .version import __version__
ModuleNotFoundError: No module named 'typhon.nonlte.version'
```

**Comment by olemke** [comment]
Fixed in PR #112.
