### ISSUE TITLE
ARTS API breaks when handling `doit_i_field`

### ISSUE THREAD

**Issue by lkluft** [atmtools/typhon#159]
## Bug report

Bug report for Freddy.

The ARTS API cannot handle `doit_i_field`. Probably because of a missing dimension.

### Code for reproduction
```python
import numpy as np
from typhon.arts.workspace import Workspace#, arts_agenda

ws=Workspace()
ws.verbositySetScreen(level=2)

# Dimension / type of atmosphere
ws.AtmosphereSet1D()

# Dimension of Stokes vector
StokesDim=1
ws.IndexSet( ws.stokes_dim, StokesDim )

za_grid=np.linspace(0,180,16)
aa_grid=np.linspace(0,360,6)

ws.VectorSet(ws.scat_za_grid, za_grid)
ws.VectorSet(ws.scat_aa_grid, aa_grid)
ws.IndexSet(ws.doit_za_grid_size,16)
ws.IndexSet(ws.cloudbox_on,1)
ws.ArrayOfIndexSet(ws.cloudbox_limits,[0,1])

ws.DoitInit()
ws.doit_i_field.value.shape
```

### Actual outcome
```
Loading ARTS API from: /Users/u300509/Documents/arts/build/src/libarts_api.so
- verbosityInit
- verbositySetScreen
- AtmosphereSet1D
  Sets the atmospheric dimensionality to 1.
- DoitInit
Traceback (most recent call last):
  File "doit_i_field_test.py", line 35, in <module>
    ws.doit_i_field.value.shape
  File "/Users/u300509/Documents/typhon/typhon/arts/workspace/workspace.py", line 294, in __getattr__
    wsv = WorkspaceVariable(i, name, group_names[group_id], description, self)
  File "/Users/u300509/Documents/typhon/typhon/arts/workspace/variables.py", line 57, in __init__
    self.update()
  File "/Users/u300509/Documents/typhon/typhon/arts/workspace/variables.py", line 275, in update
    shape.append(v.dimensions[i])
IndexError: invalid index

```

## Version information
  * Operating System: Cross-platform
  * Typhon Version: Latest github master
  * Python Version: 3.6.5

Cheers,
Lukas

**Comment by lkluft** [comment]
Fixed in 5c1489266cf382258f03b1bbe163b7744aef29c4
