### ISSUE TITLE
NetCDF4 FileHandler throws ValueError for dimensionless variables with scalar set to fill value

### ISSUE THREAD

**Issue by gerritholl** [atmtools/typhon#277]
### Bug summary

The `NetCDF4` `FileHandler` throws a `ValueError` when trying to read masked dimensionless values.  Those occur in GOES GLM L2 NetCDF files.

### Code for reproduction

```python
import xarray
from typhon.files import NetCDF4
ds = xarray.Dataset(
        {"a":
            xarray.DataArray(
                42,
                encoding={"_FillValue": 42})})
ds.to_netcdf("/tmp/spam.nc")
fh = NetCDF4()
ds2 = fh.read("/tmp/spam.nc")
```

### Actual outcome

```
Traceback (most recent call last):
  File "/hpc/uhome/gholl/miniconda3/envs/py37a/lib/python3.7/site-packages/xarray/core/variable.py", line 79, in as_variable
    obj = Variable(*obj)
  File "/hpc/uhome/gholl/miniconda3/envs/py37a/lib/python3.7/site-packages/xarray/core/variable.py", line 259, in __init__
    self._data = as_compatible_data(data, fastpath=fastpath)
  File "/hpc/uhome/gholl/miniconda3/envs/py37a/lib/python3.7/site-packages/xarray/core/variable.py", line 176, in as_compatible_data
    data[mask] = fill_value
ValueError: assignment destination is read-only

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mwe.py", line 10, in <module>
    ds2 = fh.read("/tmp/spam.nc")
  File "/hpc/uhome/gholl/miniconda3/envs/py37a/lib/python3.7/site-packages/typhon/files/handlers/common.py", line 111, in wrapper
    return method(*args, **kwargs)
  File "/hpc/uhome/gholl/miniconda3/envs/py37a/lib/python3.7/site-packages/typhon/files/handlers/common.py", line 660, in read
    self._load_group(dataset, None, root, fields)
  File "/hpc/uhome/gholl/miniconda3/envs/py37a/lib/python3.7/site-packages/typhon/files/handlers/common.py", line 718, in _load_group
    ds[path + var_name] = dims, var[:], dict(var.__dict__)
  File "/hpc/uhome/gholl/miniconda3/envs/py37a/lib/python3.7/site-packages/xarray/core/dataset.py", line 980, in __setitem__
    self.update({key: value})
  File "/hpc/uhome/gholl/miniconda3/envs/py37a/lib/python3.7/site-packages/xarray/core/dataset.py", line 2505, in update
    variables, coord_names, dims = dataset_update_method(self, other)
  File "/hpc/uhome/gholl/miniconda3/envs/py37a/lib/python3.7/site-packages/xarray/core/merge.py", line 585, in dataset_update_method
    indexes=dataset.indexes)
  File "/hpc/uhome/gholl/miniconda3/envs/py37a/lib/python3.7/site-packages/xarray/core/merge.py", line 440, in merge_core
    expanded = expand_variable_dicts(aligned)
  File "/hpc/uhome/gholl/miniconda3/envs/py37a/lib/python3.7/site-packages/xarray/core/merge.py", line 214, in expand_variable_dicts
    var = as_variable(var, name=name)
  File "/hpc/uhome/gholl/miniconda3/envs/py37a/lib/python3.7/site-packages/xarray/core/variable.py", line 84, in as_variable
    '{} to Variable.'.format(obj))
ValueError: Could not convert tuple of form (dims, data[, attrs, encoding]): ([], masked, {'_FillValue': 42}) to Variable.
```

### Expected outcome

The expected outcome would be to get an `xarray.Dataset` object with the contents of the file.

## Version information

  * Operating System: `SUSE Linux Enterprise Server 11 (x86_64), patchlevel 4`
  * Typhon Version: `0.7.0+dev13.g0c85031` (latest git master at the time of writing)
  * Python Version: `3.7.2`

I installed most through conda, but `llvmlite`, `numba`, and `typhon` through pip.

**Comment by gerritholl** [comment]
The variable in question `goes_lat_lon_projection`, is dimensionless and set to `fill_value`, which explains why it is `masked` when encountered by `typhon`.

**Comment by gerritholl** [comment]
NB: I have substantially edited the original bug report and it no longer depends on any GLM data.
