### ISSUE TITLE
NoHandlerError for CloudSat

### ISSUE THREAD

**Issue by zxdawn** [atmtools/typhon#391]
## Bug report
I tested the CloudSat 2C-ICE.P1_R05 data and it raised Handler error.

### Bug summary
Typhon can't recognize the CloudSat file.

### Code for reproduction

```python
from typhon.files import FileSet

f_cloudsat = FileSet(name='CloudSat',
                    path="../data/{satname}/"
                    '{year}{doy}{hour}{minute}{second}_*hdf'
                   )

for file in f_cloudsat:
    print(repr(file))

print(f_cloudsat["2014-07-15"])
```

### Actual outcome

```
FileInfo(
  '/student/zhangxin/papers/Arctic/data/CloudSat/2014196235839_43702_CS_2C-ICE_GRANULE_P1_R05_E06_F00.hdf',
  times=[datetime.datetime(2014, 7, 15, 23, 58, 39), datetime.datetime(2014, 7, 15, 23, 58, 39)],
  attr={'satname': 'CloudSat'}
)
Traceback (most recent call last):
  File "test_cloudsat.py", line 11, in <module>
    print(f_cloudsat["2014-07-15"])
  File "/public/home/zhangxin/new/miniconda3/envs/pyresample_min/lib/python3.8/site-packages/typhon/files/fileset.py", line 582, in __getitem__
    return self.read(filename)
  File "/public/home/zhangxin/new/miniconda3/envs/pyresample_min/lib/python3.8/site-packages/typhon/files/handlers/common.py", line 112, in wrapper
    return method(*args, **kwargs)
  File "/public/home/zhangxin/new/miniconda3/envs/pyresample_min/lib/python3.8/site-packages/typhon/files/fileset.py", line 2660, in read
    raise NoHandlerError(f"Could not read '{file_info.path}'!")
typhon.files.fileset.NoHandlerError: Could not read '/student/zhangxin/papers/Arctic/data/CloudSat/2014196235839_43702_CS_2C-ICE_GRANULE_P1_R05_E06_F00.hdf'! I do not know which file handler to use. Set one by yourself.
```

## Version information

  * Operating System: Linux
  * Typhon Version: 0.8.0
  * Python Version: 3.8.8

Installed from conda

**Comment by zxdawn** [comment]
Here's the method of reading variables from CloudSat:

```
from typhon.files import FileSet
from typhon.files import CloudSat

f_cloudsat = FileSet(name='CloudSat',
                    path="../data/{satname}/"
                    '{year}{doy}{hour}{minute}{second}_*hdf'
                   )

f_cloudsat.handler = CloudSat()

f_cloudsat.read_args={
    "fields": ["ice_water_path", ]
}

print(f_cloudsat["2014-07-15"])
```

```
<xarray.Dataset>
Dimensions:         (scnline: 37081)
Dimensions without coordinates: scnline
Data variables:
    lon             (scnline) float64 26.95 26.95 26.95 ... 2.236 2.234 2.232
    ice_water_path  (scnline) float64 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0
    lat             (scnline) float64 -0.004691 -0.01436 ... 0.01404 0.004375
    time            (scnline) datetime64[ns] 2014-07-15T23:58:40 ... 2014-07-...
```
